export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  CASHIER: "CASHIER",
};
export const STOCK_TRANSACTION_TYPES = {
  STOCK_IN: "STOCK_IN",
  STOCK_OUT: "STOCK_OUT",
  ADJUSTMENT: "ADJUSTMENT",
};
export const SALE_STATUS = {
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  RETURNED: "RETURNED",
};
export const PURCHASE_STATUS = {
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
