import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Bell, Command, LogOut, Menu, Moon, Search, Settings, Sun, ChevronDown } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { useLayout } from "../../context/layout/useLayout";
import { useAuth } from "../../context/auth/useAuth";
import { getDashboard } from "../../services/dashboard.service";
import pageTitles from "../../utils/pageTitle";
import CommandPalette from "./CommandPalette";
const Header=()=>{
 const {sidebarOpen,toggleSidebar}=useLayout(); const {user,logout}=useAuth(); const location=useLocation(); const navigate=useNavigate();
 const [commandOpen,setCommandOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[notificationOpen,setNotificationOpen]=useState(false),[theme,setTheme]=useState(()=>typeof window!=="undefined"&&localStorage.getItem("theme")==="dark"?"dark":"light"),[notifications,setNotifications]=useState([]); const menuRef=useRef(null); const previousNotificationCount=useRef(undefined); const isDarkMode=theme==="dark";
 const title=pageTitles[location.pathname]||"NexGen Warehouse"; const isDashboardRoute=location.pathname==="/dashboard"; const segments=useMemo(()=>location.pathname.split("/").filter(Boolean),[location.pathname]);
 const displayName=user?.name||user?.fullName||user?.email?.split("@")[0]||"Workspace user"; const roleName=user?.role?.name||user?.roleName||user?.role||"Operator"; const initials=displayName.split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase()||"NG";
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.classList.toggle("dark",theme==="dark");localStorage.setItem("theme",theme);},[theme]);
 useEffect(()=>{const onKeyboard=(event)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setCommandOpen(true);}};window.addEventListener("keydown",onKeyboard);return()=>window.removeEventListener("keydown",onKeyboard);},[]);
 useEffect(()=>{const onOutsideClick=(event)=>{if(menuRef.current&&!menuRef.current.contains(event.target)){setMenuOpen(false);setNotificationOpen(false);}};document.addEventListener("mousedown",onOutsideClick);return()=>document.removeEventListener("mousedown",onOutsideClick);},[]);
 useEffect(()=>{let active=true;const loadNotifications=async()=>{try{const response=await getDashboard();const items=response?.inventory?.lowStockItems||response?.alerts?.lowStock||[];if(active)setNotifications(items);}catch(error){console.error("Failed to load inventory notifications",error);}};loadNotifications();const interval=window.setInterval(loadNotifications,60000);return()=>{active=false;window.clearInterval(interval);};},[]);
 useEffect(()=>{if(!notifications.length){previousNotificationCount.current=0;return;}const count=notifications.length;if(previousNotificationCount.current!==undefined&&count>previousNotificationCount.current)toast(`Low-stock alert: ${notifications[0].name} needs replenishment.`,{icon:"⚠️",duration:4000});previousNotificationCount.current=count;},[notifications]);
 const handleLogout=()=>{setMenuOpen(false);logout();navigate("/login",{replace:true});};
 return <><header className="app-header"><div className="app-header__left"><button type="button" onClick={toggleSidebar} className="app-header__menu" aria-label={sidebarOpen?"Close navigation":"Open navigation"}><Menu size={18}/></button><div className="app-header__title-block"><div className="app-header__crumb"><span>Workspace</span>{segments.length>0&&<><b>/</b><span>{segments.map((segment)=>segment.charAt(0).toUpperCase()+segment.slice(1)).join(" / ")}</span></>}</div><h1>{isDashboardRoute?"Business overview":title}</h1></div></div>
 <div className="app-header__search-wrap"><button type="button" className="app-header__search" onClick={()=>setCommandOpen(true)} aria-label="Open command search"><Search size={17}/><span>Search pages, actions and tools...</span><kbd>Ctrl K</kbd></button></div>
 <div className="app-header__actions"><div className="app-header__notification-wrap"><button type="button" onClick={()=>setNotificationOpen((open)=>!open)} className={`app-icon-button ${notifications.length?"is-alert":""}`} aria-label={`${notifications.length} low-stock notifications`}><Bell size={18}/>{notifications.length>0&&<span className="app-header__badge">{notifications.length>9?"9+":notifications.length}</span>}</button>{notificationOpen&&<div className="app-header__popover app-header__notification-popover"><div className="app-header__popover-head"><strong>Inventory alerts</strong><span>{notifications.length} active</span></div><div className="app-header__notification-list">{notifications.slice(0,6).map((item)=><button key={item.id} type="button" onClick={()=>{setNotificationOpen(false);navigate("/inventory");}} className="app-header__notification-item"><span className="app-header__notification-icon"><AlertTriangle size={14}/></span><span><strong>{item.name}</strong><small>{item.stockQuantity} left · min {item.minimumStock}</small></span></button>)}</div></div>}</div>
 <button type="button" onClick={()=>setTheme(isDarkMode?"light":"dark")} className="app-icon-button" aria-label={`Switch to ${isDarkMode?"light":"dark"} theme`}>{isDarkMode?<Sun size={18}/>:<Moon size={18}/>}</button>
 <div className="app-user-menu" ref={menuRef}><button type="button" className="app-user-trigger" onClick={()=>setMenuOpen((open)=>!open)} aria-expanded={menuOpen}><span className="app-user-avatar">{initials}</span><span className="app-user-copy"><strong>{displayName}</strong><small>{roleName}</small></span><ChevronDown size={14}/></button>{menuOpen&&<div className="app-header__popover app-user-popover"><div className="app-user-popover__head"><span className="app-user-avatar app-user-avatar--large">{initials}</span><div><strong>{displayName}</strong><small>{user?.email||roleName}</small></div></div><button type="button" onClick={()=>{setMenuOpen(false);navigate("/settings");}}><Settings size={16}/> Settings</button><button type="button" onClick={()=>{setMenuOpen(false);setCommandOpen(true);}}><Command size={16}/> Command search</button><button type="button" className="is-danger" onClick={handleLogout}><LogOut size={16}/> Sign out</button></div>}</div></div></header><CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)}/></>;
}; export default Header;
